version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      DB_URL: jdbc:mysql://mysqldb:3306/trip_diary?allowPublicKeyRetrieval=true&useSSL=false
      DB_USER: user
      DB_PASSWORD: password
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: trip_diary
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password


